query GetAllBugsBy(
  $orderBy: [BugOrderByWithRelationInput!]
  $where: BugWhereInput!
) {
  bugs(orderBy: $orderBy, where: $where) {
    id
    title
    description
    created_at
    status
    number
    Website {
      id
      name
      url
      logo
      isPreview
    }
    user {
      first_name
      last_name
      email
    }
  }
}
